### ISSUE TITLE
order placement and execution timing is not correct (EQ, Futures)

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#2]
The system allows order placement and order execution after the trading session in both Eq & Fu.
user should not be able to place order after market session.
orders are available between:
- 9:30-2:55 for equity
- 10:00-3:00 for Futures
![14](https://user-images.githubusercontent.com/84329389/210942350-ea4bcd5c-4edd-43d4-85f1-4a59d1afee2a.PNG)

**Comment by Samiaatieh** [comment]
Done please check it and let me know your feedback

**Comment by mnf1980** [comment]
it is working fine right now with Eq, please update the Future as well.

**Comment by mnf1980** [comment]
problem is back again; the SIM allow to trade on pre-open!

**update1:**
I can trade equity after session hours!

**update2:** 
putting Future order after 2:45 is generating an error "Market is closed now."
Future should be enabled from 10:00 to 3:00

![29](https://user-images.githubusercontent.com/84329389/218378579-08455c5e-4e4d-4c9c-a7a7-953525d92624.png)

**Comment by Samiaatieh** [comment]
Fixed for adx market

for adx derv please send exctly the times for per open,open,perclosed ,closed

**Comment by mnf1980** [comment]
I'm still able to put order (no execution) after 3:00. there are more logic for orders and execution between 2:55-3:00, please find the chart below for more details:
**for Eq:**
      - between 2:45-2:55 order only, no execution
      - 2:55 ADX reveal the closing price
      - 2:55-3:00 trade only at closing price
      - no orders allowed after 3:00 or before 9:30 

**For Futures:**
- trading from 10:00 - 3:00
- no pre-open, no pre-close
- no orders allowed after 3:00 or before 9:30 
![ADX (2)](https://user-images.githubusercontent.com/84329389/218720379-8708533d-7622-4a63-a61c-906e1ce3f2c0.jpg)

**Comment by Samiaatieh** [comment]
Setting on the market level to allow me from 9:30 to 3:00  for placing, modifying, and canceling, done as showing on below screenshot .

 You check 2:45-2:55 if the order becomes completed ?!?!

![image](https://user-images.githubusercontent.com/122079188/218938639-80d11ed1-13fc-45ec-92c7-735585a5aa8a.png)

**Comment by mnf1980** [comment]
i will try it today and let you know

**Comment by mnf1980** [comment]
by the way **MKT orders** are not allowed in pre-open/close

**Comment by Samiaatieh** [comment]
Done added the rules as you requested

**Comment by mnf1980** [comment]
- The system is not allowing to put orders between 2:45:2:55!
- The system is not allowing to modify orders quantity between 2:55 to 3:00 if the price is same as the closing price.

**The correct behavior is:**
 - between 2:45-2:55 order only, no execution (create, delete or edit orders freely)
- 2:55-3:00 trade only at closing price (put new order @ close price, modify orders @ close price, delete orders, execute @ close price)


![33](https://user-images.githubusercontent.com/84329389/220246245-3ddaf3d3-cdbf-4d23-a4ff-cd952905ab55.png)
![34](https://user-images.githubusercontent.com/84329389/220246527-a193b914-c9cb-40eb-ad61-6a61edeab00a.png)

**Comment by mnf1980** [comment]
please find the update logic

![ADX (3)](https://user-images.githubusercontent.com/84329389/221098191-26b3cd8a-9fbd-425c-84d4-1a36bef52448.jpg)

**Comment by Samiaatieh** [comment]
Done please check it
