### ISSUE TITLE
total profit is not calculated correctly

### ISSUE THREAD

**Issue by mnf1980** [mnf1980/SIM#36]
please check the picture: total loss should be 537.37. there are no opened positions.

![31](https://user-images.githubusercontent.com/84329389/218719274-d6f758a4-c5bd-47ac-8ee2-bac2fc41c553.png)

**Comment by Samiaatieh** [comment]
Done please check it

**Comment by mnf1980** [comment]
problem is still exist,
need a meeting to explain in more details

**Comment by mnf1980** [comment]
i think you need to do the same fix to the future side also, as the profit is calculated with the commission from futures. 


![39](https://user-images.githubusercontent.com/84329389/223094992-e4a72f12-512a-437c-a9c6-60fe62ce4abc.png)

**Comment by Samiaatieh** [comment]
![image](https://user-images.githubusercontent.com/122079188/232723601-4a63ca87-5751-43fb-b906-3e9a5c1526e2.png)
there is VAT for future

**Comment by Samiaatieh** [comment]
done
